# Generated by Django 4.0.8 on 2023-04-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeys',
            name='user',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
